version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: America/Mexico_City
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: ts-jest
    versions:
    - 26.5.2
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.23
    - 0.20.25
  - dependency-name: eslint
    versions:
    - 7.19.0
