title: sambo-site
description: >
  A Discord.js-powered Discord client framework
baseurl: "/localization"
url: "https://discord-sambo.github.io/localization/"

collections:
  guides:
    permalink: /guides/:title/
    output: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

sass:
  style: compressed

include:
  - "*.html" # Needed to include files that start with underscore

exclude:
  - images/edit
  - Gemfile
  - Gemfile.lock
  - README.md
  - typedoc
