name: Build Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: Install Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: Install dependencies
        run: |
          npm install
          rm -rf ./node_modules/typedoc/node_modules/typescript
          cp -r ./node_modules/typescript ./node_modules/typedoc/node_modules/typescript

      - name: Build docs
        run: npm run docs
      
      - name: Clone gh-pages branch
        run: git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git -b gh-pages ../gh-pages
      
      - name: Prepare docs build
        run: npx gulp gh-docs-prepare

      - name: Check if commit is needed
        id: git_status
        run: |
          cd ../gh-pages
          echo "##[set-output name=status;]$(git status | grep 'nothing to commit')"

      - name: Make commit and push
        if: contains(steps.git_status.outputs.status, 'nothing to commit') != true
        run: |
          cd ../gh-pages
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor}}@users.noreply.github.com"
          git add --all
          git commit -m "Build docs from master: ${{ github.sha }}"
          git push origin gh-pages
